# Dockerfile for Nginx
FROM nginx:alpine

# Copy custom Nginx configuration
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /var/www/html

    # Set permissions
RUN chown -R nginx:nginx /var/www/html \
    && chmod -R 755 /var/www/html

# Expose port 80
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]